export const types = [
  "Universidade",
  "Instituto de Pesquisa",
  "Empresa",
  "Associação",
  "Centro de Inovação",
  "Startup",
  "Incubadora",
];
export const states = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];
export const emptyInstitution = {
  name: "",
  cnpj: "",
  founded: "",
  status: "",
  email: "",
  phone: "",
  site: "",
  street: "",
  number: "",
  neighborhood: "",
  city: "",
  state: "",
  zip: "",
  complement: "",
  type: "",
  area: "",
  description: "",
};
const rows = [
  [
    "Universidade Nova",
    "contato@uninova.edu.br",
    "12.456.788/0001-81",
    "Universidade",
    "Guarapuava",
    "Ativa",
  ],
  [
    "Instituto Alpha",
    "alpha@contato.org.br",
    "12.387.998/0001-01",
    "Instituto de Pesquisa",
    "Guarapuava",
    "Ativa",
  ],
  [
    "Empresa Inovação",
    "inovacao_empresa@outlook.com.br",
    "45.673.184/0001-02",
    "Empresa",
    "Irati",
    "Inativa",
  ],
  [
    "Universidade Prudentópolis",
    "contato@uniprudentopolis.edu.br",
    "64.173.188/0001-08",
    "Universidade",
    "Prudentópolis",
    "Ativa",
  ],
  [
    "Associação de Entre Rios",
    "contato@entreriosassocia.org.br",
    "47.894.213/0001-61",
    "Associação",
    "Guarapuava",
    "Ativa",
  ],
  [
    "Empresa Tech",
    "tech_emp@gmail.com",
    "94.613.702/0001-43",
    "Empresa",
    "Laranjeiras do Sul",
    "Inativa",
  ],
  [
    "Universidade Goioxim",
    "contato@universidadegoioxim.edu.br",
    "46.422.709/0001-11",
    "Universidade",
    "Goioxim",
    "Inativa",
  ],
  [
    "Centro de Pesquisa",
    "contato@pesquisacentro.com.br",
    "77.113.884/0001-99",
    "Instituto de Pesquisa",
    "Prudentópolis",
    "Ativa",
  ],
  [
    "Universidade Iratiense",
    "contato@iratienseuni.edu.br",
    "77.133.445/0001-66",
    "Universidade",
    "Irati",
    "Ativa",
  ],
];
export const initialInstitutions = rows.map(
  ([name, email, cnpj, type, city, status], i) => ({
    ...emptyInstitution,
    id: String(i + 1),
    name,
    email,
    cnpj,
    type,
    city,
    status,
    state: "PR",
    ...(i === 0
      ? {
          founded: "1998-03-15",
          phone: "(42) 3633-3333",
          site: "www.uninova.com.br",
          street: "Rua das Chaves",
          number: "123",
          neighborhood: "Centro",
          zip: "80000-000",
          complement: "Bloco A - Reitoria",
          area: "Educação",
          description:
            "A Universidade Nova é uma instituição de ensino superior voltada à formação acadêmica e profissional, oferecendo cursos de graduação e pós-graduação em diferentes áreas do conhecimento. A instituição busca promover uma educação de qualidade, incentivando a inovação, a pesquisa e o desenvolvimento de seus estudantes.",
        }
      : {}),
    createdAt: "2025-04-22T09:54:00",
    updatedAt: "2026-07-17T16:02:00",
  }),
);
export const meetings = [
  {
    id: 1,
    day: "12",
    name: "Reunião Mensal do Ecossistema",
    description: "Reunião geral com todos os participantes",
    time: "13:00",
    place: "Auditório",
    address: "Prefeitura de Guarapuava",
    count: 115,
  },
  {
    id: 2,
    day: "12",
    name: "Comitê de Inovação",
    description: "Discussão de projetos",
    time: "16:00",
    place: "Sala de Reuniões 1",
    address: "Centro de Inovação",
    count: 32,
  },
  {
    id: 3,
    day: "14",
    name: "Reunião com Startups",
    description: "Apresentação de avanço das startups",
    time: "10:45",
    place: "Sala de Reuniões 1",
    address: "Centro de Inovação",
    count: 14,
  },
  {
    id: 4,
    day: "14",
    name: "Encontro com Incubadoras",
    description: "Reunião com representantes de incubadoras",
    time: "14:30",
    place: "Sala de Reuniões",
    address: "Centro de Inovação Campo Real",
    count: 8,
  },
];
